### ISSUE TITLE
DMA: Add full support for all peripherals

### ISSUE THREAD

**Issue by hannobraun** [lpc-rs/lpc8xx-hal#118]
Currently, there's only some basic DMA support for USART. DMA support should be added for all peripherals where this is possible, with a nice API.

**Comment by hannobraun** [comment]
I'm inclined to close this issue. It would be useful if it registered a specific need for a user, or to track remaining work if there were just a few implementations missing (and an ongoing effort to provide them). But as it stands, this issue is not useful. We already know that the HAL is not feature-complete.

@david-sawatzke Thoughts?

**Comment by david-sawatzke** [comment]
Since this is pretty much a feature request, I don't care much either way
