### ISSUE TITLE
Deprecate lpc82x-hal

### ISSUE THREAD

**Issue by david-sawatzke** [lpc-rs/lpc8xx-hal#182]
@hannobraun There's no notice on [crates.io](https://crates.io/crates/lpc82x-hal) that it's deprecated

**Comment by hannobraun** [comment]
Good catch. I'll take care of it.

**Comment by david-sawatzke** [comment]
Something minor thing: The github blurb still suggests that this crate is only for lpc82x

**Comment by hannobraun** [comment]
> Some minor thing: The github blurb still suggests that this crate is only for lpc82x

Fixed.

**Comment by david-sawatzke** [comment]
Had a quick look over the issues, ping @hannobraun

**Comment by hannobraun** [comment]
Thanks, I haven't forgotten. I've just been busy enough these past months that everything not on the critical path has fallen by the wayside.

Looks like things might start to clear up for me soon, so I hope this won't stay open much longer.

**Comment by hannobraun** [comment]
Done!
