### ISSUE TITLE
Publish new version on crates.io

### ISSUE THREAD

**Issue by papyDoctor** [lpc-rs/lpc8xx-hal#335]
Please upgrade your crate at crates.io because the cortex-m dependency is not the same as here
(0.6.4 on crates.io and 0.7.2 here)
Thank you

**Comment by hannobraun** [comment]
Thanks for letting us know, @papyDoctor! I've added publishing a new version to my task list. Might take a bit until I can get to it though. I recommend depending on the Git repository directly in the meantime.

**Comment by hannobraun** [comment]
I've opened #336. Currently waiting on review.
