### ISSUE TITLE
Implement digital input

### ISSUE THREAD

**Issue by hannobraun** [lpc-rs/lpc8xx-hal#50]
The GPIO peripheral supports both digital input and output (as the name obviously implies). Currently, only output is implemented, but it should be relatively straight-forward to extend the API to support input.

Even though this is a pretty basic feature, I'm marking this issue as low-priority, as I don't have a use for it right now, and I haven't heard from anyone who does. If you need this feature, please post a comment in this issue. I'll happily increase the priority, if anyone needs this.

**Comment by hdoordt** [comment]
I'd like to use this feature

**Comment by david-sawatzke** [comment]
@hdoordt Will soon be implemented via #189
