### ISSUE TITLE
Pin output API might be too restrictive

### ISSUE THREAD

**Issue by hannobraun** [lpc-rs/lpc8xx-hal#53]
The current API only allows for setting the output level when the pin is in the output state. This seems sensible at first, but it might cause the wrong output level to be set for a moment, right after the pin has entered the output state, but right before the desired output level has been set. Depending on the application, this might be a problem.

I think it may be better to make `set_high` and `set_low` available regardless of pin direction. However, if that change is made, I wonder if it still makes sense to encode the pin direction as a type parameter at all.

I'd love to hear more opinions about this design issue! Please leave a comment, especially if you have relevant practical experience.

**Comment by somemetricprefix** [comment]
Without knowing the current design:
Maybe pass an initial state to the function that configures the PIN as output.
HAL then updates the state before changing to output mode.
This inital state could be high, low or unspecified. unspecified would then just skip to change the state before configuring the pin as output.

**Comment by hannobraun** [comment]
@somemetricprefix Yeah, that could work. If we use a generic parameter for the initial state, we could even make it zero-cost, if "unspecified" is passed. Thank you!
